blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://discord.gg/6Fy6AJMbMU
    about: Please ask and answer questions in our Discord server
  - name: Security issue
    url: mailto:hello@pixelfed.org
    about: Please notify us about security issue by email at hello@pixelfed.org

