name: Android build

on:
  push:
    branches: [ main, '@kwasow/CI' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      # - name: 🏗 Enable corepack
      #   run: corepack enable

      - name: 🏗 Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 📦 Install dependencies
        run: npm install
      
      - name: 🔑 Inject secrets
        run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: 🚀 Build app
        run: |
          cd android
          ./gradlew assembleDebug
