name: Android build

on:
  push:
    branches: [ main, '@kwasow/CI' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm install
      
      - name: 🔑 Inject secrets
        run: echo $GOOGLE_SERVICES_JSON > google-services.json

      - name: 🚀 Build app
        run: npx expo run:android
