name: iOS build

on:
  push:
    branches: [ main, '@kwasow/CI' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build app
        run: eas build --non-interactive --local --platform ios
