name: iOS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      # - name: 🏗 Enable corepack
      #   run: corepack enable

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm install
      
      - name: 🔑 Inject secrets
        run: echo $GOOGLE_SERVICES_PLIST > ios/GoogleService-Info.plist.json
        env:
          GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}

      - name: 🚀 Build app
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.1.app/Contents/Developer
          cd ios
          pod install
          set -o pipefail && xcodebuild -workspace pixelfed.xcworkspace -scheme pixelfed -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" | xcbeautify --renderer github-actions
