name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      
      # - name: 🏗 Enable corepack
      #   run: corepack enable

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧹 Run biomejs
        run: npm run lint-check
